[package]
authors.workspace    = true
description          = "Common types for testing CosmWasm smart contracts on MANTRA Chain"
edition.workspace    = true
homepage.workspace   = true
keywords             = ["mantrachain", "mantra", "testing", "cosmwasm"]
license.workspace    = true
name                 = "mantra-common-testing"
repository.workspace = true
version              = "1.1.3"

[dependencies]
anyhow.workspace          = true
cosmwasm-schema.workspace = true
cosmwasm-std.workspace    = true
cw-multi-test.workspace   = true
mantra-dex-std.workspace  = true
osmosis-std.workspace     = true
schemars.workspace        = true
serde.workspace           = true
