[package]
authors.workspace    = true
description          = "Types used by the MANTRA-dex contracts suite"
edition.workspace    = true
homepage.workspace   = true
keywords             = ["mantrachain", "mantra", "dex", "amm", "cosmwasm"]
license.workspace    = true
name                 = "mantra-dex-std"
repository.workspace = true
version              = "2.1.5"

[dependencies]
anybuf.workspace          = true
cosmwasm-schema.workspace = true
cosmwasm-std.workspace    = true
cw-ownable.workspace      = true
cw-storage-plus.workspace = true
osmosis-std.workspace     = true
uint.workspace            = true

[dev-dependencies]
test-case.workspace = true
